### PR TITLE
Interface, Send: add warning for sweep button fee overriddance

### PR DESCRIPTION
**Pull request by MarnixCroes**
Issue that comes up a lot for users, so mention it in the docs
image

### CODE REVIEW

**Comment by MarnixCroes** [comment]
I'm aware of https://github.com/joinmarket-webui/jam/issues/761 / https://github.com/joinmarket-webui/jam/pull/764

still good to add it to the docs

**Comment by theborakompanioni** [comment]
> I'm aware of [joinmarket-webui/jam#761](https://github.com/joinmarket-webui/jam/issues/761) / [joinmarket-webui/jam#764](https://github.com/joinmarket-webui/jam/pull/764)
> 
> still good to add it to the docs

Thanks @MarnixCroes! Yes, good to add it to the docs.
The issue/PR you linked is also still waiting for better suggestions on how to phrase it properly. I think we should be more precise on why it might lead to a higher-than-expected mining fee. What do you think?

**Comment by MarnixCroes** [comment]
@theborakompanioni 
sorry for late reply.
I've added more info for clarification

**Review by theborakompanioni — APPROVED** [review]
:ok_hand: 

Reminded me to make the max change fee setting configurable in Jam. Thanks again! :pray:

**Pull request merged**
